### PR TITLE
Fix filter so logical operations are constructed correctly

### PR DESCRIPTION
**Pull request by jazdw**
See the following gist for what this fixes. Also allows for nicer filter.or({key: value}) type filtering.

https://gist.github.com/jazdw/2410f64b99fbd9c104fa

### CODE REVIEW

**Comment by jazdw** [comment]
Note that #121 is related, perhaps sort and limit should be added to Filter as another operator type (so you would create them as filter.limit(10,20) for example) and then the whole query log could just be joined using filterCreator('and').apply(Filter.prototype, queryLog)

**Comment by kriszyp** [comment]
This looks like an excellent improvement to filtering. However, it looks like a unit testing is failing. Would you mind taking a look at the failing unit test?

**Comment by kriszyp** [comment]
Or is this dependent on #121 to address the unit test failure?

**Comment by jazdw** [comment]
Hey Kris, the or method will work slightly differently now. I've fixed the unit test. I think it reads more naturally?
condition1.or(condition2) => OR(condition1, condition2)
condition1.or(condition2, condition3) => OR(condition1, condition2, condition3)
instead of
condition1.or(condition2) => AND(condition1, OR(condition2))
condition1.or(condition2, that2) => AND(condition1, OR(condition2, condition3))

**Comment by kriszyp** [comment]
Looks good, thank you!

**Pull request merged**
